### ISSUE TITLE
Requires `setPrototypeOf`

### ISSUE THREAD

**Issue by wavebeem** [sgentle/catenary#1]
Trying this in the version of node I had installed broke because the code relies on `setPrototypeOf`. It would also break in Safari, IE<11, and both mobile Chrome and mobile Safari.

I haven't looked close enough to see if the library could be rewritten without using `setPrototypeOf`, so sorry if this is fundamental.

```
💩  node -v
v0.10.35

💩  node
> require('catenary')
TypeError: Object function Object() { [native code] } has no method 'setPrototypeOf'
  at Catenary (/Users/brian/node_modules/catenary/catenary.coffee.md:70:12)
  at Object.<anonymous> (/Users/brian/node_modules/catenary/catenary.coffee.md:158:20)
  at Object.<anonymous> (/Users/brian/node_modules/catenary/catenary.coffee.md:182:4)
  at Module._compile (module.js:456:26)
  at Object.loadFile (/Users/brian/node_modules/catenary/node_modules/coffee-script/lib/coffee-script/register.js:16:19)
  at Module.load (/Users/brian/node_modules/catenary/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/Users/brian/node_modules/catenary/index.js:2:18)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at repl:1:2
  at REPLServer.self.eval (repl.js:110:21)
  at Interface.<anonymous> (repl.js:239:12)
  at Interface.emit (events.js:95:17)
  at Interface._onLine (readline.js:203:10)
  at Interface._line (readline.js:532:8)
  at Interface._ttyWrite (readline.js:761:14)
  at ReadStream.onkeypress (readline.js:100:10)
  at ReadStream.emit (events.js:98:17)
  at emitKey (readline.js:1096:12)
  at ReadStream.onData (readline.js:841:14)
  at ReadStream.emit (events.js:95:17)
  at ReadStream.<anonymous> (_stream_readable.js:765:14)
  at ReadStream.emit (events.js:92:17)
  at emitReadable_ (_stream_readable.js:427:10)
  at emitReadable (_stream_readable.js:423:5)
  at readableAddChunk (_stream_readable.js:166:9)
  at ReadStream.Readable.push (_stream_readable.js:128:10)
  at TTY.onread (net.js:529:21)
```

**Comment by sgentle** [comment]
Nicely caught. I'll add a polyfill.

**Comment by wavebeem** [comment]
I blinked and you came in and fixed it! :hammer: :wrench: 

[According to MDN, this should fix everything except IE<11](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/proto?redirectlocale=en-US&redirectslug=JavaScript%2FReference%2FGlobal_Objects%2FObject%2Fproto). Might be worth mentioning intended browser support in the README.

**Comment by sgentle** [comment]
Yeah definitely. I think to do that I'd want actual browser tests first. I've set up #6 to track that.
